FROM ruby:3.0.6-alpine3.16
WORKDIR /app

RUN apk add build-base libxml2-dev libxslt-dev git bash file imagemagick libpq libxml2 libxslt nodejs sqlite-dev tini tzdata yarn
# RUN bundle install
# RUN bundle exec rails assets:precompile
# RUN bundle exec rails db:migrate

ENTRYPOINT ["sh"]
EXPOSE 3000
